version: '3.8'

services:
  diplomacy:
    build:
      context: .
    ports:
      - 8000:8000
      - 9229:9229
    environment:
      - SERVER_PORT=8000
    command: npm run debug
    volumes:
      - type: bind
        source: .
        target: /app